// <auto-generated />
namespace Entidad.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addTotalPrecio : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTotalPrecio));
        
        string IMigrationMetadata.Id
        {
            get { return "201703110528318_add-TotalPrecio"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
